<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="T_ClassThatRaisesNotifications" Id="{c11d4f62-058c-42a7-933f-c523f0c1c82d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK T_ClassThatRaisesNotifications
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
    OnPbPressed_Notification : T_Notification; 
    PbIdentifier : STRING := 'CP23';
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="OnPressedNotification" Id="{0a0297c3-1d14-421b-907e-fde2e3a09660}">
      <Declaration><![CDATA[PROPERTY OnPressedNotification : I_Notification]]></Declaration>
      <Get Name="Get" Id="{7eecedc7-374a-4e06-8352-9faeb9bd5856}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[OnPressedNotification := OnPbPressed_Notification;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Method Name="RaiseOnPbPressedNotification" Id="{804c7876-622a-42b7-ad87-f6ef097ca46f}">
      <Declaration><![CDATA[METHOD RaiseOnPbPressedNotification
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[OnPbPressed_Notification.Args
    .Clear()
    .Add_STRING(PbIdentifier);
OnPbPressed_Notification.Raise();]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>