<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="TUnsupportedEventHandler" Id="{9c2e5d32-b5a9-43b0-b18a-e8571f4432bb}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK TUnsupportedEventHandler IMPLEMENTS IUnsupportedEventHandler
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>