<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="TUnsupportedEventHandler" Id="{7946d37f-3e20-44e9-80d4-790f5f9013c7}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK TUnsupportedEventHandler IMPLEMENTS IUnsupportedEventHandler
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>