<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="F_DINT_TO_UDINT" Id="{dd87d6bf-a853-4d68-a3ac-b6aba78de549}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_DINT_TO_UDINT : UDINT
VAR_INPUT
    value : DINT;
END_VAR
VAR
    inRangeValue : DINT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[inRangeValue := MAX(0,value);
F_DINT_TO_UDINT := DINT_TO_UDINT(inRangeValue);
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>