<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="F_ReadAndClear" Id="{463f69b5-0d65-483a-9f34-d8ace50c5d79}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_ReadAndClear : BOOL
VAR_IN_OUT
	Flag : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_ReadAndClear := Flag;
Flag           := FALSE;
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>