<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="F_ReadFlag" Id="{4b3f26af-7445-48e5-b269-ceb5ef85d1ba}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_ReadFlag : BOOL // Reads a boolean and clears it if set
VAR_IN_OUT
	Flag : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_ReadFlag := Flag;
Flag       := FALSE;
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>