<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="PB_TestRunner" Id="{63470fcc-b57d-026d-334d-1963f895812d}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PB_TestRunner
VAR
    // Functions...
    Test_F_DINT_TO_UDINT_Conversion : Test_F_DINT_TO_UDINT_Conversion;
    Test_F_UDINT_TO_DINT_Conversion : Test_F_UDINT_TO_DINT_Conversion;
    
    // TStream
    Test_TStream_Add_Read_BLOB          : Test_TStreamAdd_Read_BLOB;
    Test_TStream_Add_Read_BOOL          : Test_TStreamAdd_Read_BOOL;
    Test_TStream_Add_Read_BYTE          : Test_TStreamAdd_Read_BYTE;
    Test_TStream_Add_Read_INT           : Test_TStreamAdd_Read_INT;
    Test_TStream_Add_Read_UINT          : Test_TStreamAdd_Read_UINT;
    Test_TStream_Add_Read_DINT          : Test_TStreamAdd_Read_DINT;
    Test_TStream_Add_Read_UDINT         : Test_TStreamAdd_Read_UDINT;
    Test_TStream_Add_Read_REAL          : Test_TStreamAdd_Read_REAL;
    Test_TStream_Add_Read_LREAL         : Test_TStreamAdd_Read_LREAL;
    Test_TStream_Add_Read_STRING        : Test_TStreamAdd_Read_STRING;
    Test_TStream_Add_Read_Short_STRING  : Test_TStreamAdd_Read_Short_STRING;
    Test_TStream_Add_Read_T_MaxString   : Test_TStreamAdd_Read_T_MaxString;
    Test_TStream_Add_Read_LINT          : Test_TStreamAdd_Read_LINT;
    Test_TStream_Add_Read_ULINT         : Test_TStreamAdd_Read_ULINT;
    Test_TStream_Add_Read_PVOID         : Test_TStreamAdd_Read_PVOID;
    Test_TStream_BufferResizes          : Test_TStreamBufferResizes;

    // TEventBase...
    Test_TEvent_AddHandlerAddsHandlerToEventHandlerList     : Test_TEvent_AddHandlerAddsHandlerToEventHandlerList;
    Test_TListOfEventHandlers_StoresAndRetreivesHandlers    : Test_TListOfEventHandlers_StoresAndRetreivesHandlers;  
    Test_TEvent_AddEventHandler_ChecksInterfaceSupported    : Test_TEvent_AddEventHandler_ChecksInterfaceSupported; 
    Test_TEvent_AddEventHandler_ResizesListWhenListFull     : Test_TEvent_AddEventHandler_ResizesListWhenListFull;
    Test_TEvent_AddEventHandler_IncsNumberOfEventHandlers   : Test_TEvent_AddEventHandler_IncsNumberOfEventHandlers;
    Test_TEventHandler_HandlesRaisedEvent                   : Test_TEventHandler_HandlesRaisedEvent;
    Test_TEventHandler_HandlesRaisedEvent_UsingEventArgs    : Test_TEventHandler_HandlesRaisedEvent_UsingEventArgs;

    // TExecution
    Test_TExecution_WhenBusy_Abort_SelectsAborting     : Test_TExecutionWhenBusy_Abort_SelectsAborting;
    Test_TExecution_WhenBusy_SetAborted_RaisesEvent    : Test_TExecutionWhenBusy_SetAborted_RaisesEvent;
    Test_TExecution_WhenBusy_SetDone_SetsDone          : Test_TExecutionWhenBusy_SetDone_SetsDone;
    Test_TExecution_WhenBusy_SetError_RaisesEvent      : Test_TExecutionWhenBusy_SetError_RaisesEvent;
    Test_TExecution_WhenBusy_Start_RaisesEvent         : Test_TExecutionWhenBusy_Start_RaisesEvent;
    Test_TExecution_WhenReady_Start_SelectsStarting    : Test_TExecutionWhenReady_Start_SelectsStarting;
    
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[tcl_SimpleUnitTestLibrary.TestFramework.TestRunner(RunTestsSequentially := TRUE);


]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>