<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="T_TestSuite" Id="{70a6f186-bf9f-446b-b8ad-6a94cd0284ed}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'no_explicit_call' := 'do not call this POU directly'} 
FUNCTION_BLOCK T_TestSuite
VAR
    Test_AggregateResult_Ready                      : Test_AggregateResult_Ready;
    Test_AggregateResult_Starting                   : Test_AggregateResult_Starting;
    Test_AggregateResult_Busy                       : Test_AggregateResult_Busy;
    Test_AggregateResult_Done                       : Test_AggregateResult_Done;
    Test_AggregateResult_Error                      : Test_AggregateResult_Error;
    Test_AggregateResult_ErrorMsg                   : Test_AggregateResult_ErrorMsg;
    Test_AggregateResult_Aborting                   : Test_AggregateResult_Aborting;
    Test_AggregateResult_Aborted                    : Test_AggregateResult_Aborted;
    Test_TExecution_WhenBusy_Abort_SelectsAborting  : Test_TExecutionWhenBusy_Abort_SelectsAborting;
    Test_TExecution_WhenBusy_SetDone_SetsDone       : Test_TExecutionWhenBusy_SetDone_SetsDone;
    Test_TExecution_WhenReady_Start_SelectsStarting : Test_TExecutionWhenReady_Start_SelectsStarting;
    Test_TExecution_SetErrorHandlesString_ErrorId   : Test_TExecution_SetErrorHandlesString_ErrorId;
    Test_F_DINT_TO_UDINT_Conversion                 : Test_F_DINT_TO_UDINT_Conversion;
    Test_F_UDINT_TO_DINT_Conversion                 : Test_F_UDINT_TO_DINT_Conversion;
    Test_F_Equals                                   : Test_F_Equals;
    Test_F_NotEqual                                 : Test_F_NotEqual;
    Test_ErrorIdToString                            : Test_ErrorIdToString;
    Test_NotificationNoArgs                         : Test_NotificationNoArgs;
    Test_NotificationWithStringArg                  : Test_NotificationWithStringArg;
    Test_NotificationCountWithQueueingEnabled       : Test_NotificationCountWithQueueingEnabled;
    Test_MultipleNotificationsWithStringArgs        : Test_MultipleNotificationsWithStringArgs;
    Test_NotificationHandlerOnlyAddedOnce           : Test_NotificationHandlerOnlyAddedOnce;

    Test_TStreamAdd_Read_BLOB                 : Test_TStreamAdd_Read_BLOB;
    Test_TStreamAdd_Read_BLOB_CheckAlignment  : Test_TStreamAdd_Read_BLOB_CheckAlignment;
    Test_TStreamAdd_Read_BOOL                 : Test_TStreamAdd_Read_BOOL;
    Test_TStreamAdd_Read_BYTE                 : Test_TStreamAdd_Read_BYTE;
    Test_TStreamAdd_Read_DINT                 : Test_TStreamAdd_Read_DINT;
    Test_TStreamAdd_Read_DINT_CheckAlignment  : Test_TStreamAdd_Read_DINT_CheckAlignment;
    Test_TStreamAdd_Read_INT                  : Test_TStreamAdd_Read_INT;
    Test_TStreamAdd_Read_INT_CheckAlignment   : Test_TStreamAdd_Read_INT_CheckAlignment;
    Test_TStreamAdd_Read_LINT                 : Test_TStreamAdd_Read_LINT;
    Test_TStreamAdd_Read_LINT_CheckAlignment  : Test_TStreamAdd_Read_LINT_CheckAlignment;
    Test_TStreamAdd_Read_LREAL                : Test_TStreamAdd_Read_LREAL;
    Test_TStreamAdd_Read_LREAL_CheckAlignment : Test_TStreamAdd_Read_LREAL_CheckAlignment;
    Test_TStreamAdd_Read_PVOID                : Test_TStreamAdd_Read_PVOID;
    Test_TStreamAdd_Read_PVOID_CheckAlignment : Test_TStreamAdd_Read_PVOID_CheckAlignment;
    Test_TStreamAdd_Read_REAL                 : Test_TStreamAdd_Read_REAL;
    Test_TStreamAdd_Read_REAL_CheckAlignment  : Test_TStreamAdd_Read_REAL_CheckAlignment;
    Test_TStreamAdd_Read_Short_STRING         : Test_TStreamAdd_Read_Short_STRING;
    Test_TStreamAdd_Read_STRING               : Test_TStreamAdd_Read_STRING;
    Test_TStreamAdd_Read_T_MaxString          : Test_TStreamAdd_Read_T_MaxString;
    Test_TStreamAdd_Read_UDINT                : Test_TStreamAdd_Read_UDINT;
    Test_TStreamAdd_Read_UDINT_CheckAlignment : Test_TStreamAdd_Read_UDINT_CheckAlignment;
    Test_TStreamAdd_Read_UINT                 : Test_TStreamAdd_Read_UINT;
    Test_TStreamAdd_Read_UINT_CheckAlignment  : Test_TStreamAdd_Read_UINT_CheckAlignment;
    Test_TStreamAdd_Read_ULINT                : Test_TStreamAdd_Read_ULINT;
    Test_TStreamAdd_Read_ULINT_CheckAlignment : Test_TStreamAdd_Read_ULINT_CheckAlignment;
    Test_TStreamAddReadArgType                : Test_TStreamAddReadArgType;
    Test_TStreamAddReadArgType_CheckAlignment : Test_TStreamAddReadArgType_CheckAlignment;
    Test_TStreamBufferResizes                 : Test_TStreamBufferResizes;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="RunTests" Id="{4b4a0afb-16f7-4d56-bd76-d23e71f119fb}">
      <Declaration><![CDATA[METHOD RunTests
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[Test_AggregateResult_Ready                     		.RunTest();
Test_AggregateResult_Starting                       .RunTest();
Test_AggregateResult_Busy                           .RunTest();
Test_AggregateResult_Done                           .RunTest();
Test_AggregateResult_Error                          .RunTest();
Test_AggregateResult_ErrorMsg                       .RunTest();
Test_AggregateResult_Aborting                       .RunTest();
Test_AggregateResult_Aborted                        .RunTest();
Test_TExecution_WhenBusy_Abort_SelectsAborting      .RunTest();
Test_TExecution_WhenBusy_SetDone_SetsDone           .RunTest();
Test_TExecution_WhenReady_Start_SelectsStarting     .RunTest();
Test_TExecution_SetErrorHandlesString_ErrorId       .RunTest();
Test_F_DINT_TO_UDINT_Conversion                     .RunTest();
Test_F_UDINT_TO_DINT_Conversion                     .RunTest();
Test_F_Equals                                       .RunTest();
Test_F_NotEqual                                     .RunTest();
Test_ErrorIdToString                                .RunTest();
Test_NotificationNoArgs                             .RunTest();
Test_NotificationWithStringArg                      .RunTest();
Test_NotificationCountWithQueueingEnabled           .RunTest();
Test_MultipleNotificationsWithStringArgs            .RunTest();
Test_NotificationHandlerOnlyAddedOnce               .RunTest();

Test_TStreamAdd_Read_BLOB                			.RunTest();
Test_TStreamAdd_Read_BLOB_CheckAlignment            .RunTest();
Test_TStreamAdd_Read_BOOL                           .RunTest();
Test_TStreamAdd_Read_BYTE                           .RunTest();
Test_TStreamAdd_Read_DINT                           .RunTest();
Test_TStreamAdd_Read_DINT_CheckAlignment            .RunTest();
Test_TStreamAdd_Read_INT                            .RunTest();
Test_TStreamAdd_Read_INT_CheckAlignment             .RunTest();
Test_TStreamAdd_Read_LINT                           .RunTest();
Test_TStreamAdd_Read_LINT_CheckAlignment            .RunTest();
Test_TStreamAdd_Read_LREAL                          .RunTest();
Test_TStreamAdd_Read_LREAL_CheckAlignment           .RunTest();
Test_TStreamAdd_Read_PVOID                          .RunTest();
Test_TStreamAdd_Read_PVOID_CheckAlignment           .RunTest();
Test_TStreamAdd_Read_REAL                           .RunTest();
Test_TStreamAdd_Read_REAL_CheckAlignment            .RunTest();
Test_TStreamAdd_Read_Short_STRING                   .RunTest();
Test_TStreamAdd_Read_STRING                         .RunTest();
Test_TStreamAdd_Read_T_MaxString                    .RunTest();
Test_TStreamAdd_Read_UDINT                          .RunTest();
Test_TStreamAdd_Read_UDINT_CheckAlignment           .RunTest();
Test_TStreamAdd_Read_UINT                           .RunTest();
Test_TStreamAdd_Read_UINT_CheckAlignment            .RunTest();
Test_TStreamAdd_Read_ULINT                          .RunTest();
Test_TStreamAdd_Read_ULINT_CheckAlignment           .RunTest();
Test_TStreamAddReadArgType                          .RunTest();
Test_TStreamAddReadArgType_CheckAlignment           .RunTest();
Test_TStreamBufferResizes                           .RunTest();






]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>