<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="TUnsupportedEventHandler" Id="{a93b148c-62d8-436a-a14f-f2e39d309283}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK TUnsupportedEventHandler IMPLEMENTS IUnsupportedEventHandler
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>